#
# CheckGPResultRemote.ps1
#
$ErrorActionPreference = "Continue"
Try
{
    $Servers = Get-ADComputer -SearchBase "OU=KNG-CORP,OU=Application_Servers,OU=Servers,OU=Nieuwe Omgeving,DC=lwmeijer,DC=cag" -Filter * -SearchScope Subtree
    $sqlServiceInfo = @()

    foreach ($server in $Servers)
    {
		Try
		{
			$serverName = $server.SamAccountName.Replace("$","")
			#get groupmemberships of server computer object
			$groupMemberships = Get-ADPrincipalGroupMembership -Identity $server.SamAccountName

			Write-Host "Group Membership of server $($server.SamAccountName)" -ForegroundColor Green
			foreach ($group in $groupMemberships)
			{
				Write-Host $group.Name -ForegroundColor Red
			}
			Write-Host "------------------------------------------------------------------------`r"

			#temporary path where xml is stored, generated by RSoP
			$tempXMLPath = "C:\Temp\GPResults\$serverName.xml"
        
			Write-Host "Get RSoP data from server $serverName" -ForegroundColor Green
			Get-GPResultantSetOfPolicy -Computer $serverName -ReportType Xml -Path $tempXMLPath -User "lwmeijer\Administrator" -ErrorAction Continue | Out-Null

			[xml]$xml = Get-Content -Path $tempXMLPath

			#get group membership of computer object
			$groups = $xml.Rsop.ComputerResults.SecurityGroup.Name

			Write-Host "Discovered groups in the GP Resultant Set of server $($server.Name)" -ForegroundColor Green
			Write-Host (($groups.'#text').Where{$_ -like "*SG_LWM*"}).Replace("LWMEIJER\","")
			Write-Host "------------------------------------------------------------------------`r"

			Write-Host "Start compare of the actual group membership vs group memberships configured in AD:" -ForegroundColor Green
			Compare-Object -ReferenceObject (($groupMemberships.Name).Where{$_ -like "*SG_LWM*"} | Sort-Object) `
			-DifferenceObject ((($groups.'#text').Where{$_ -like "*SG_LWM*"}).Replace("LWMEIJER\","") | Sort-Object) -PassThru

			Write-Host "`r`r`r`r`r`r"
			#if ($groups."#text" -like "*AllServers*")
			#{
			#    Write-Host "$serverName is member of AllServers group and membership is visible on server RSoP"
			#}
			#else
			#{
			#    Write-Host "$serverName might be member of AllServers group but membership is not visible on server RSoP"
			#}

			#Remove-Item -Path $tempXMLPath -Force
		}
		Catch
		{
			$ErrorActionPreference = "Continue"
			Write-Host "Error occured:" -ForegroundColor Yellow
			$Error			
		}
    }
}
catch
{
    Write-Host "TERMINATING ERROR OCCURED" -ForegroundColor DarkRed -BackgroundColor Cyan
    $Error
}
finally
{
    Write-Host "Script ended"
}

Function WriteLog ([string]$message, [string]$logPath)
{

}